{
  "id":23,
  "name":"mf_tenniscourts",
  "formtabs":[
    {
      "MIGX_id":29,
      "caption":"Type",
      "print_before_tabs":1,
      "fields":[
        {
          "MIGX_id":123,
          "field":"parent",
          "caption":"",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"hidden",
          "validation":"",
          "configs":"",
          "restrictive_condition":"",
          "display":"",
          "sourceFrom":"config",
          "sources":"",
          "inputOptionValues":"",
          "default":10,
          "pos":1
        },
        {
          "MIGX_id":126,
          "field":"facility_type",
          "caption":"",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"migxhidden_fix",
          "validation":"",
          "configs":"",
          "restrictive_condition":"",
          "display":"",
          "sourceFrom":"config",
          "sources":"",
          "inputOptionValues":"",
          "default":"TennisCourt",
          "pos":2
        }
      ],
      "pos":1
    },
    {
      "MIGX_id":33,
      "caption":"Facility",
      "print_before_tabs":"0",
      "fields":[
        {
          "MIGX_id":132,
          "field":"pagetitle",
          "caption":"Name",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"",
          "validation":"",
          "configs":"",
          "restrictive_condition":"",
          "display":"",
          "sourceFrom":"config",
          "sources":"",
          "inputOptionValues":"",
          "default":"",
          "pos":1
        },
        {
          "MIGX_id":134,
          "field":"Facility_address",
          "caption":"Address",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"textarea",
          "validation":"",
          "configs":"",
          "restrictive_condition":"",
          "display":"",
          "sourceFrom":"config",
          "sources":"",
          "inputOptionValues":"",
          "default":"",
          "pos":2
        }
      ],
      "pos":2
    },
    {
      "MIGX_id":31,
      "caption":"Tennis Court",
      "print_before_tabs":"0",
      "fields":[
        {
          "MIGX_id":127,
          "field":"TennisCourt_number_of_courts",
          "caption":"Number of Courts",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"",
          "validation":"",
          "configs":"",
          "restrictive_condition":"",
          "display":"",
          "sourceFrom":"config",
          "sources":"",
          "inputOptionValues":"",
          "default":"",
          "pos":1
        },
        {
          "MIGX_id":128,
          "field":"TennisCourt_surface_type",
          "caption":"Surface Type",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"",
          "validation":"",
          "configs":"",
          "restrictive_condition":"",
          "display":"",
          "sourceFrom":"config",
          "sources":"",
          "inputOptionValues":"",
          "default":"",
          "pos":2
        }
      ],
      "pos":3
    }
  ],
  "contextmenus":"update||recall_remove_delete",
  "actionbuttons":"addItem",
  "columnbuttons":"",
  "filters":"",
  "extended":{
    "migx_add":"Add Facility",
    "disable_add_item":"",
    "formcaption":"",
    "update_win_title":"",
    "win_id":"",
    "maxRecords":"",
    "addNewItemAt":"bottom",
    "multiple_formtabs":"24||23",
    "actionbuttonsperrow":4,
    "winbuttonslist":"",
    "extrahandlers":"",
    "filtersperrow":4,
    "packageName":"migxfacilities",
    "classname":"facilityResource",
    "task":"facilities",
    "getlistsort":"",
    "getlistsortdir":"",
    "sortconfig":"",
    "gridpagesize":"",
    "use_custom_prefix":"0",
    "prefix":"",
    "grid":"",
    "gridload_mode":1,
    "check_resid":1,
    "check_resid_TV":"",
    "join_alias":"",
    "has_jointable":"yes",
    "getlistwhere":{
      "parent":10
    },
    "joins":[
      {
        "alias":"Facility"
      },
      {
        "alias":"TennisCourt",
        "classname":"mfTennisCourt",
        "on":"TennisCourt.facility_id=Facility.id"
      }
    ],
    "cmpmaincaption":"Facilities",
    "cmptabcaption":"Facilities",
    "cmptabdescription":"",
    "cmptabcontroller":"",
    "winbuttons":"",
    "onsubmitsuccess":"",
    "submitparams":""
  },
  "columns":[
    {
      "MIGX_id":1,
      "header":"ID",
      "dataIndex":"id",
      "width":10,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderchunktpl":"",
      "renderoptions":""
    },
    {
      "MIGX_id":2,
      "header":"Name",
      "dataIndex":"pagetitle",
      "width":30,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderchunktpl":"",
      "renderoptions":""
    }
  ],
  "createdby":1,
  "createdon":"2014-10-03 11:43:14",
  "editedby":1,
  "editedon":"2014-10-03 14:55:44",
  "deleted":0,
  "deletedon":"-1-11-30 00:00:00",
  "deletedby":0,
  "published":1,
  "publishedon":"2014-10-03 01:00:00",
  "publishedby":0
}